---
title: Rust基础12 Result类处理错误
---
Rust 提供了用于返回和传播错误的 `Result<T, E>` 枚举。 按照惯例，`Ok(T)` 变量表示成功并包含一个值，而变量 `Err(E)` 表示错误并包含一个错误值。

`Result<T, E>` 枚举定义为：
```rust
enum Result<T, E> {
    Ok(T):  // A value T was obtained.
    Err(E): // An error of type E was encountered instead.
}
```
不同于描述缺少某个值的可能性的 `Option` 类型，`Result` 类型最适合在可能会失败时使用。
`Result` 类型还具有 `unwrap` 和 `expect` 方法，这些方法执行以下操作之一：
- 返回 `Ok` 变量中的值。
- 如果变体是 `Err`，则导致程序 panic。
让我们看一下实际操作中的 `Result`。 下面的示例代码中实现了 `safe_division` 函数，该函数返回以下任一内容：
- 变体为 `Ok` 的 `Result` 值，该变体携带了成功的除法运算的结果。
- 一个 `Err` 变体，它携带了一个结构 `DivisionByZeroError`，该结构指示除法运算不成功。

```rust
#[derive(Debug)]
struct DivisionByZeroError;

fn safe_division(dividend: f64, divisor: f64) -> Result<f64, DivisionByZeroError> {
    if divisor == 0.0 {
        Err(DivisionByZeroError)
    } else {
        Ok(dividend / divisor)
    }
}

fn main() {
    println!("{:?}", safe_division(9.0, 3.0));
    println!("{:?}", safe_division(4.0, 0.0));
    println!("{:?}", safe_division(0.0, 2.0));
}
```
输出表明：
```
Ok(3.0)
Err(DivisionByZeroError)
Ok(0.0)
```
`DivisionByZeroError` 结构之前的 `#[derive(Debug)]` 部分是一个宏，指示 Rust 编译器将类型设置为可输出，以便进行调试。 我们稍后会在“特征”模块中深入讨论此概念。
